CONFIG_HN_SPI2C=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_DATA_CONTAINER=y
CONFIG_SPI=y
CONFIG_SPI_NXP_LPSPI=y
CONFIG_SPI_NXP_LPSPI_DMA=n
CONFIG_DMA=y
CONFIG_SPI_ASYNC=y
CONFIG_SPI_SLAVE=y
CONFIG_GPIO=y
CONFIG_CRC=y
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_MAX_SPI2C_TRANSACTION_SIZE=512
CONFIG_SPEED_OPTIMIZATIONS=y
