CONFIG_HN_SPI2C=y
CONFIG_SPI2C_CUSTOM_REGISTER_AMT=0
CONFIG_SPI2C_INTERNAL_REGISTER_AMT=2
CONFIG_SPI=y
CONFIG_I2C=y
CONFIG_SPI_NXP_LPSPI=y
CONFIG_SPI_NXP_LPSPI_DMA=n
CONFIG_SPI_ASYNC=y
CONFIG_TSYS01_SENSOR=y
CONFIG_SPI_SLAVE=y
CONFIG_GPIO=y
CONFIG_PRINTK=y
CONFIG_CRC=y
CONFIG_LOG=n
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_THREAD_NAME=y
CONFIG_THREAD_MONITOR=y
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_LOG_PRINTK=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BUFFER_SIZE=4096
