CONFIG_HN_HSUSB=y
# Enable the USB device stack
CONFIG_USB_DEVICE_STACK=y

CONFIG_SPEED_OPTIMIZATIONS=y

CONFIG_USB_DEVICE_VID=0xFFFF          
CONFIG_USB_DEVICE_PID=0x4712          
CONFIG_USB_DEVICE_PRODUCT="MCXN_HS_USB" # Product string
CONFIG_USB_DEVICE_MANUFACTURER="CSB"   # Manufacturer string

# Disable other USB classes so only yours registers
CONFIG_USB_CDC_ACM=n
CONFIG_USB_DEVICE_HID=n
CONFIG_USB_DEVICE_BLUETOOTH=n

# Buffer size must accommodate your largest packet
CONFIG_USB_REQUEST_BUFFER_SIZE=512

CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
